// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookToLibrary(arg1) {
  return window['go']['main']['App']['AddBookToLibrary'](arg1);
}

export function ExtractEPUBMetadata(arg1) {
  return window['go']['main']['App']['ExtractEPUBMetadata'](arg1);
}

export function GetBooks() {
  return window['go']['main']['App']['GetBooks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
