// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';

export function AddBookToLibrary(arg1:library.Metadata):Promise<void>;

export function ExtractEPUBMetadata(arg1:string):Promise<library.Metadata>;

export function GetBooks():Promise<Array<library.Metadata>>;

export function Greet(arg1:string):Promise<string>;
